apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-single-app
spec:
  destination:
    name: ''
    namespace: single-userapp
    server: 'https://kubernetes.default.svc'
  source:
    path: multi-cluster/app-copy-distribution/Argocd
    repoURL: 'https://github.com/wangyuan249/my-gitops-comparison.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
